package com.yz.sophia.insight.dao;

import com.yz.sophia.insight.model.po.*;

import java.util.List;
import java.util.Map;

import com.yz.sophia.insight.model.response.ApplyApplicationRelResp;
import org.apache.ibatis.annotations.Param;

public interface ApplyApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int countByExample(ApplyApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int deleteByExample(ApplyApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int insert(ApplyApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int insertSelective(ApplyApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    List<ApplyApplication> selectByExample(ApplyApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    ApplyApplicationRelResp selectByPrimaryKey(@Param(value="applicationCode") String applicationCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApplyApplication record, @Param("example") ApplyApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApplyApplication record, @Param("example") ApplyApplicationExample example);

    int updateStatusByExample(@Param("record") ApplyApplication record, @Param("example") ApplyApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApplyApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_application
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApplyApplication record);

    /**
     * 查询条数
     * @param map
     * @return
     */
    int countByParam(Map<String,Object> map);

    /**
     * 查询分页
     * @param
     * @return
     */
//    List<ApplyApplicationQo> selectPageByParam(Map<String, Object> map);

    /**
     * 分页查询
     */
    List<ApplyApplication> selectPageByExample(ApplyApplicationExample example);
}