package com.yz.sophia.insight.dao;

import com.yz.sophia.insight.model.po.LegalInstrument;
import com.yz.sophia.insight.model.po.LegalInstrumentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LegalInstrumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int countByExample(LegalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int deleteByExample(LegalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int insert(LegalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int insertSelective(LegalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    List<LegalInstrument> selectByExample(LegalInstrumentExample example);

    /**
     * 分页查询
     */
    List<LegalInstrument> selectPageByExample(LegalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    LegalInstrument selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LegalInstrument record, @Param("example") LegalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LegalInstrument record, @Param("example") LegalInstrumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LegalInstrument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LegalInstrument record);
}