package com.yz.sophia.stargaze.dao;

import com.yz.sophia.stargaze.model.po.CockpitNavigationMenu;
import com.yz.sophia.stargaze.model.po.CockpitNavigationMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CockpitNavigationMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int countByExample(CockpitNavigationMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int deleteByExample(CockpitNavigationMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int insert(CockpitNavigationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int insertSelective(CockpitNavigationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    List<CockpitNavigationMenu> selectByExample(CockpitNavigationMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    CockpitNavigationMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CockpitNavigationMenu record, @Param("example") CockpitNavigationMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CockpitNavigationMenu record, @Param("example") CockpitNavigationMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CockpitNavigationMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_navigation_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CockpitNavigationMenu record);
}