package com.yz.sophia.stargaze.dao;

import com.yz.sophia.stargaze.model.po.PoiArea;
import com.yz.sophia.stargaze.model.po.PoiAreaExample;
import com.yz.sophia.stargaze.model.response.POIProvinceDetailResp;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PoiAreaMapper {

    List<POIProvinceDetailResp> countProvincePoints(PoiAreaExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int countByExample(PoiAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int deleteByExample(PoiAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long dataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int insert(PoiArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int insertSelective(PoiArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    List<PoiArea> selectByExample(PoiAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    PoiArea selectByPrimaryKey(Long dataid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PoiArea record, @Param("example") PoiAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PoiArea record, @Param("example") PoiAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PoiArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poi_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PoiArea record);
}