package com.yz.sophia.stargaze.dao;

import com.yz.sophia.stargaze.model.po.SophiaOpenService;
import com.yz.sophia.stargaze.model.po.SophiaOpenServiceExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SophiaOpenServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int countByExample(SophiaOpenServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int deleteByExample(SophiaOpenServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int insert(SophiaOpenService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int insertSelective(SophiaOpenService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    List<SophiaOpenService> selectByExample(SophiaOpenServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    SophiaOpenService selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SophiaOpenService record, @Param("example") SophiaOpenServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SophiaOpenService record, @Param("example") SophiaOpenServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SophiaOpenService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sophia_open_service
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SophiaOpenService record);
}