package com.yz.sophia.insight.model.po;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel("应用申请")
public class ApplyApplication {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("主键id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.create_time
     *
     * @mbggenerated
     */
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty("修改時間")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("用户id")
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.application_code
     *
     * @mbggenerated
     */
    @ApiModelProperty("应用code")
    private String applicationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.application_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("应用名称")
    private String applicationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.application_type
     *
     * @mbggenerated
     */
    @ApiModelProperty("应用类型")
    private String applicationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.application_describe
     *
     * @mbggenerated
     */
    @ApiModelProperty("应用描述")
    private String applicationDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.audit_status
     *
     * @mbggenerated
     */
    @ApiModelProperty("审核状态（0=待审核，1=审核通过，2=审核不通过）")
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_application.status
     *
     * @mbggenerated
     */
    @ApiModelProperty("状态（-1=删除，0=正常）")
    private Integer status;

    @ApiModelProperty("应用平台（1=ios,2=android,3=h5,4=小程序,5=其他 ; 使用|分割）")
    private String applicationService;

    @ApiModelProperty("公匙")
    private String apiKey;

    @ApiModelProperty("私匙")
    private String secretKey;

    public String getApplicationService() {
        return applicationService;
    }

    public void setApplicationService(String applicationService) {
        this.applicationService = applicationService;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public String getSecretKey() {
        return secretKey;
    }

    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.id
     *
     * @return the value of apply_application.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.id
     *
     * @param id the value for apply_application.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.create_time
     *
     * @return the value of apply_application.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.create_time
     *
     * @param createTime the value for apply_application.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.update_time
     *
     * @return the value of apply_application.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.update_time
     *
     * @param updateTime the value for apply_application.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.user_id
     *
     * @return the value of apply_application.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.user_id
     *
     * @param userId the value for apply_application.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.application_code
     *
     * @return the value of apply_application.application_code
     *
     * @mbggenerated
     */
    public String getApplicationCode() {
        return applicationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.application_code
     *
     * @param applicationCode the value for apply_application.application_code
     *
     * @mbggenerated
     */
    public void setApplicationCode(String applicationCode) {
        this.applicationCode = applicationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.application_name
     *
     * @return the value of apply_application.application_name
     *
     * @mbggenerated
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.application_name
     *
     * @param applicationName the value for apply_application.application_name
     *
     * @mbggenerated
     */
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.application_type
     *
     * @return the value of apply_application.application_type
     *
     * @mbggenerated
     */
    public String getApplicationType() {
        return applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.application_type
     *
     * @param applicationType the value for apply_application.application_type
     *
     * @mbggenerated
     */
    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.application_describe
     *
     * @return the value of apply_application.application_describe
     *
     * @mbggenerated
     */
    public String getApplicationDescribe() {
        return applicationDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.application_describe
     *
     * @param applicationDescribe the value for apply_application.application_describe
     *
     * @mbggenerated
     */
    public void setApplicationDescribe(String applicationDescribe) {
        this.applicationDescribe = applicationDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.audit_status
     *
     * @return the value of apply_application.audit_status
     *
     * @mbggenerated
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.audit_status
     *
     * @param auditStatus the value for apply_application.audit_status
     *
     * @mbggenerated
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_application.status
     *
     * @return the value of apply_application.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_application.status
     *
     * @param status the value for apply_application.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}