package com.yz.sophia.insight.model.po;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("地理信息城市对象")
public class GeographicCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.id
     *
     * @mbggenerated
     */
    @ApiModelProperty("主键id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.city_id
     *
     * @mbggenerated
     */
    @ApiModelProperty("城市id")
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.city_name
     *
     * @mbggenerated
     */
    @ApiModelProperty("城市名称")
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.longitude
     *
     * @mbggenerated
     */
    @ApiModelProperty("经度")
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.latitude
     *
     * @mbggenerated
     */
    @ApiModelProperty("纬度")
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.rainfall_year
     *
     * @mbggenerated
     */
    @ApiModelProperty("全年降雨量（毫米）")
    private Double rainfallYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column geographic_city.sunlight_year
     *
     * @mbggenerated
     */
    @ApiModelProperty("全年日照小时数（小时）")
    private Double sunlightYear;

    @ApiModelProperty("省份")
    private String cityProvince;

    public String getCityProvince() {
        return cityProvince;
    }

    public void setCityProvince(String cityProvince) {
        this.cityProvince = cityProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.id
     *
     * @return the value of geographic_city.id
     *
     * @mbggenerated
     */


    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.id
     *
     * @param id the value for geographic_city.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.city_id
     *
     * @return the value of geographic_city.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.city_id
     *
     * @param cityId the value for geographic_city.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.city_name
     *
     * @return the value of geographic_city.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.city_name
     *
     * @param cityName the value for geographic_city.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.longitude
     *
     * @return the value of geographic_city.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.longitude
     *
     * @param longitude the value for geographic_city.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.latitude
     *
     * @return the value of geographic_city.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.latitude
     *
     * @param latitude the value for geographic_city.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.rainfall_year
     *
     * @return the value of geographic_city.rainfall_year
     *
     * @mbggenerated
     */
    public Double getRainfallYear() {
        return rainfallYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.rainfall_year
     *
     * @param rainfallYear the value for geographic_city.rainfall_year
     *
     * @mbggenerated
     */
    public void setRainfallYear(Double rainfallYear) {
        this.rainfallYear = rainfallYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column geographic_city.sunlight_year
     *
     * @return the value of geographic_city.sunlight_year
     *
     * @mbggenerated
     */
    public Double getSunlightYear() {
        return sunlightYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column geographic_city.sunlight_year
     *
     * @param sunlightYear the value for geographic_city.sunlight_year
     *
     * @mbggenerated
     */
    public void setSunlightYear(Double sunlightYear) {
        this.sunlightYear = sunlightYear;
    }

    @Override
    public String toString() {
        return "GeographicCity{" +
                "id=" + id +
                ", cityId='" + cityId + '\'' +
                ", cityName='" + cityName + '\'' +
                ", longitude=" + longitude +
                ", latitude=" + latitude +
                ", rainfallYear=" + rainfallYear +
                ", sunlightYear=" + sunlightYear +
                ", cityProvince='" + cityProvince + '\'' +
                '}';
    }
}