package com.yz.sophia.insight.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LegalInstrumentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected int offset = 0;

    protected int pageSize = 10;

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public LegalInstrumentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeIsNull() {
            addCriterion("judgment_code is null");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeIsNotNull() {
            addCriterion("judgment_code is not null");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeEqualTo(String value) {
            addCriterion("judgment_code =", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeNotEqualTo(String value) {
            addCriterion("judgment_code <>", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeGreaterThan(String value) {
            addCriterion("judgment_code >", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("judgment_code >=", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeLessThan(String value) {
            addCriterion("judgment_code <", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeLessThanOrEqualTo(String value) {
            addCriterion("judgment_code <=", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeLike(String value) {
            addCriterion("judgment_code like", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeNotLike(String value) {
            addCriterion("judgment_code not like", value, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeIn(List<String> values) {
            addCriterion("judgment_code in", values, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeNotIn(List<String> values) {
            addCriterion("judgment_code not in", values, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeBetween(String value1, String value2) {
            addCriterion("judgment_code between", value1, value2, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andJudgmentCodeNotBetween(String value1, String value2) {
            addCriterion("judgment_code not between", value1, value2, "judgmentCode");
            return (Criteria) this;
        }

        public Criteria andLawCauseIsNull() {
            addCriterion("law_cause is null");
            return (Criteria) this;
        }

        public Criteria andLawCauseIsNotNull() {
            addCriterion("law_cause is not null");
            return (Criteria) this;
        }

        public Criteria andLawCauseEqualTo(String value) {
            addCriterion("law_cause =", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseNotEqualTo(String value) {
            addCriterion("law_cause <>", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseGreaterThan(String value) {
            addCriterion("law_cause >", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseGreaterThanOrEqualTo(String value) {
            addCriterion("law_cause >=", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseLessThan(String value) {
            addCriterion("law_cause <", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseLessThanOrEqualTo(String value) {
            addCriterion("law_cause <=", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseLike(String value) {
            addCriterion("law_cause like", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseNotLike(String value) {
            addCriterion("law_cause not like", value, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseIn(List<String> values) {
            addCriterion("law_cause in", values, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseNotIn(List<String> values) {
            addCriterion("law_cause not in", values, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseBetween(String value1, String value2) {
            addCriterion("law_cause between", value1, value2, "lawCause");
            return (Criteria) this;
        }

        public Criteria andLawCauseNotBetween(String value1, String value2) {
            addCriterion("law_cause not between", value1, value2, "lawCause");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeIsNull() {
            addCriterion("submission_time is null");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeIsNotNull() {
            addCriterion("submission_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeEqualTo(Date value) {
            addCriterion("submission_time =", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeNotEqualTo(Date value) {
            addCriterion("submission_time <>", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeGreaterThan(Date value) {
            addCriterion("submission_time >", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("submission_time >=", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeLessThan(Date value) {
            addCriterion("submission_time <", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeLessThanOrEqualTo(Date value) {
            addCriterion("submission_time <=", value, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeIn(List<Date> values) {
            addCriterion("submission_time in", values, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeNotIn(List<Date> values) {
            addCriterion("submission_time not in", values, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeBetween(Date value1, Date value2) {
            addCriterion("submission_time between", value1, value2, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andSubmissionTimeNotBetween(Date value1, Date value2) {
            addCriterion("submission_time not between", value1, value2, "submissionTime");
            return (Criteria) this;
        }

        public Criteria andBelongCourtIsNull() {
            addCriterion("belong_court is null");
            return (Criteria) this;
        }

        public Criteria andBelongCourtIsNotNull() {
            addCriterion("belong_court is not null");
            return (Criteria) this;
        }

        public Criteria andBelongCourtEqualTo(String value) {
            addCriterion("belong_court =", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtNotEqualTo(String value) {
            addCriterion("belong_court <>", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtGreaterThan(String value) {
            addCriterion("belong_court >", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtGreaterThanOrEqualTo(String value) {
            addCriterion("belong_court >=", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtLessThan(String value) {
            addCriterion("belong_court <", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtLessThanOrEqualTo(String value) {
            addCriterion("belong_court <=", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtLike(String value) {
            addCriterion("belong_court like", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtNotLike(String value) {
            addCriterion("belong_court not like", value, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtIn(List<String> values) {
            addCriterion("belong_court in", values, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtNotIn(List<String> values) {
            addCriterion("belong_court not in", values, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtBetween(String value1, String value2) {
            addCriterion("belong_court between", value1, value2, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andBelongCourtNotBetween(String value1, String value2) {
            addCriterion("belong_court not between", value1, value2, "belongCourt");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeIsNull() {
            addCriterion("judgment_type is null");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeIsNotNull() {
            addCriterion("judgment_type is not null");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeEqualTo(String value) {
            addCriterion("judgment_type =", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeNotEqualTo(String value) {
            addCriterion("judgment_type <>", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeGreaterThan(String value) {
            addCriterion("judgment_type >", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("judgment_type >=", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeLessThan(String value) {
            addCriterion("judgment_type <", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeLessThanOrEqualTo(String value) {
            addCriterion("judgment_type <=", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeLike(String value) {
            addCriterion("judgment_type like", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeNotLike(String value) {
            addCriterion("judgment_type not like", value, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeIn(List<String> values) {
            addCriterion("judgment_type in", values, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeNotIn(List<String> values) {
            addCriterion("judgment_type not in", values, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeBetween(String value1, String value2) {
            addCriterion("judgment_type between", value1, value2, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentTypeNotBetween(String value1, String value2) {
            addCriterion("judgment_type not between", value1, value2, "judgmentType");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberIsNull() {
            addCriterion("judgment_number is null");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberIsNotNull() {
            addCriterion("judgment_number is not null");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberEqualTo(String value) {
            addCriterion("judgment_number =", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberNotEqualTo(String value) {
            addCriterion("judgment_number <>", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberGreaterThan(String value) {
            addCriterion("judgment_number >", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberGreaterThanOrEqualTo(String value) {
            addCriterion("judgment_number >=", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberLessThan(String value) {
            addCriterion("judgment_number <", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberLessThanOrEqualTo(String value) {
            addCriterion("judgment_number <=", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberLike(String value) {
            addCriterion("judgment_number like", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberNotLike(String value) {
            addCriterion("judgment_number not like", value, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberIn(List<String> values) {
            addCriterion("judgment_number in", values, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberNotIn(List<String> values) {
            addCriterion("judgment_number not in", values, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberBetween(String value1, String value2) {
            addCriterion("judgment_number between", value1, value2, "judgmentNumber");
            return (Criteria) this;
        }

        public Criteria andJudgmentNumberNotBetween(String value1, String value2) {
            addCriterion("judgment_number not between", value1, value2, "judgmentNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table legal_instrument
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table legal_instrument
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}