package com.yz.sophia.insight.model.po;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
@ApiModel("法律案件文书对象")
public class LegalInstrument {

    @ApiModelProperty("主键id")
    private Long id;

    @ApiModelProperty("案件code")
    private String judgmentCode;

    @ApiModelProperty("案由")
    private String lawCause;

    @ApiModelProperty("提交日期")
    private Date submissionTime;

    @ApiModelProperty("所属法院")
    private String belongCourt;

    @ApiModelProperty("判决书类型")
    private String judgmentType;

    @ApiModelProperty("案号")
    private String judgmentNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.id
     *
     * @return the value of legal_instrument.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.id
     *
     * @param id the value for legal_instrument.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.judgment_code
     *
     * @return the value of legal_instrument.judgment_code
     *
     * @mbggenerated
     */
    public String getJudgmentCode() {
        return judgmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.judgment_code
     *
     * @param judgmentCode the value for legal_instrument.judgment_code
     *
     * @mbggenerated
     */
    public void setJudgmentCode(String judgmentCode) {
        this.judgmentCode = judgmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.law_cause
     *
     * @return the value of legal_instrument.law_cause
     *
     * @mbggenerated
     */
    public String getLawCause() {
        return lawCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.law_cause
     *
     * @param lawCause the value for legal_instrument.law_cause
     *
     * @mbggenerated
     */
    public void setLawCause(String lawCause) {
        this.lawCause = lawCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.submission_time
     *
     * @return the value of legal_instrument.submission_time
     *
     * @mbggenerated
     */
    public Date getSubmissionTime() {
        return submissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.submission_time
     *
     * @param submissionTime the value for legal_instrument.submission_time
     *
     * @mbggenerated
     */
    public void setSubmissionTime(Date submissionTime) {
        this.submissionTime = submissionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.belong_court
     *
     * @return the value of legal_instrument.belong_court
     *
     * @mbggenerated
     */
    public String getBelongCourt() {
        return belongCourt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.belong_court
     *
     * @param belongCourt the value for legal_instrument.belong_court
     *
     * @mbggenerated
     */
    public void setBelongCourt(String belongCourt) {
        this.belongCourt = belongCourt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.judgment_type
     *
     * @return the value of legal_instrument.judgment_type
     *
     * @mbggenerated
     */
    public String getJudgmentType() {
        return judgmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.judgment_type
     *
     * @param judgmentType the value for legal_instrument.judgment_type
     *
     * @mbggenerated
     */
    public void setJudgmentType(String judgmentType) {
        this.judgmentType = judgmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_instrument.judgment_number
     *
     * @return the value of legal_instrument.judgment_number
     *
     * @mbggenerated
     */
    public String getJudgmentNumber() {
        return judgmentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_instrument.judgment_number
     *
     * @param judgmentNumber the value for legal_instrument.judgment_number
     *
     * @mbggenerated
     */
    public void setJudgmentNumber(String judgmentNumber) {
        this.judgmentNumber = judgmentNumber;
    }
}