package com.yz.sophia.insight.model.po;

import java.util.ArrayList;
import java.util.List;

public class MultilevelMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public MultilevelMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMenusCodeIsNull() {
            addCriterion("menus_code is null");
            return (Criteria) this;
        }

        public Criteria andMenusCodeIsNotNull() {
            addCriterion("menus_code is not null");
            return (Criteria) this;
        }

        public Criteria andMenusCodeEqualTo(String value) {
            addCriterion("menus_code =", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeNotEqualTo(String value) {
            addCriterion("menus_code <>", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeGreaterThan(String value) {
            addCriterion("menus_code >", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("menus_code >=", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeLessThan(String value) {
            addCriterion("menus_code <", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeLessThanOrEqualTo(String value) {
            addCriterion("menus_code <=", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeLike(String value) {
            addCriterion("menus_code like", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeNotLike(String value) {
            addCriterion("menus_code not like", value, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeIn(List<String> values) {
            addCriterion("menus_code in", values, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeNotIn(List<String> values) {
            addCriterion("menus_code not in", values, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeBetween(String value1, String value2) {
            addCriterion("menus_code between", value1, value2, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusCodeNotBetween(String value1, String value2) {
            addCriterion("menus_code not between", value1, value2, "menusCode");
            return (Criteria) this;
        }

        public Criteria andMenusNameIsNull() {
            addCriterion("menus_name is null");
            return (Criteria) this;
        }

        public Criteria andMenusNameIsNotNull() {
            addCriterion("menus_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenusNameEqualTo(String value) {
            addCriterion("menus_name =", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameNotEqualTo(String value) {
            addCriterion("menus_name <>", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameGreaterThan(String value) {
            addCriterion("menus_name >", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameGreaterThanOrEqualTo(String value) {
            addCriterion("menus_name >=", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameLessThan(String value) {
            addCriterion("menus_name <", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameLessThanOrEqualTo(String value) {
            addCriterion("menus_name <=", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameLike(String value) {
            addCriterion("menus_name like", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameNotLike(String value) {
            addCriterion("menus_name not like", value, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameIn(List<String> values) {
            addCriterion("menus_name in", values, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameNotIn(List<String> values) {
            addCriterion("menus_name not in", values, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameBetween(String value1, String value2) {
            addCriterion("menus_name between", value1, value2, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusNameNotBetween(String value1, String value2) {
            addCriterion("menus_name not between", value1, value2, "menusName");
            return (Criteria) this;
        }

        public Criteria andMenusRankIsNull() {
            addCriterion("menus_rank is null");
            return (Criteria) this;
        }

        public Criteria andMenusRankIsNotNull() {
            addCriterion("menus_rank is not null");
            return (Criteria) this;
        }

        public Criteria andMenusRankEqualTo(Integer value) {
            addCriterion("menus_rank =", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankNotEqualTo(Integer value) {
            addCriterion("menus_rank <>", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankGreaterThan(Integer value) {
            addCriterion("menus_rank >", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("menus_rank >=", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankLessThan(Integer value) {
            addCriterion("menus_rank <", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankLessThanOrEqualTo(Integer value) {
            addCriterion("menus_rank <=", value, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankIn(List<Integer> values) {
            addCriterion("menus_rank in", values, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankNotIn(List<Integer> values) {
            addCriterion("menus_rank not in", values, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankBetween(Integer value1, Integer value2) {
            addCriterion("menus_rank between", value1, value2, "menusRank");
            return (Criteria) this;
        }

        public Criteria andMenusRankNotBetween(Integer value1, Integer value2) {
            addCriterion("menus_rank not between", value1, value2, "menusRank");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeIsNull() {
            addCriterion("parent_menus_code is null");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeIsNotNull() {
            addCriterion("parent_menus_code is not null");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeEqualTo(String value) {
            addCriterion("parent_menus_code =", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeNotEqualTo(String value) {
            addCriterion("parent_menus_code <>", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeGreaterThan(String value) {
            addCriterion("parent_menus_code >", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("parent_menus_code >=", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeLessThan(String value) {
            addCriterion("parent_menus_code <", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeLessThanOrEqualTo(String value) {
            addCriterion("parent_menus_code <=", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeLike(String value) {
            addCriterion("parent_menus_code like", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeNotLike(String value) {
            addCriterion("parent_menus_code not like", value, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeIn(List<String> values) {
            addCriterion("parent_menus_code in", values, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeNotIn(List<String> values) {
            addCriterion("parent_menus_code not in", values, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeBetween(String value1, String value2) {
            addCriterion("parent_menus_code between", value1, value2, "parentMenusCode");
            return (Criteria) this;
        }

        public Criteria andParentMenusCodeNotBetween(String value1, String value2) {
            addCriterion("parent_menus_code not between", value1, value2, "parentMenusCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table multilevel_menu
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table multilevel_menu
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}