package com.yz.sophia.insight.model.po;

import java.util.Date;

public class ProductInsight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.product_category
     *
     * @mbggenerated
     */
    private String productCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.product_brand
     *
     * @mbggenerated
     */
    private String productBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.product_platform
     *
     * @mbggenerated
     */
    private String productPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.product_model
     *
     * @mbggenerated
     */
    private String productModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.product_store
     *
     * @mbggenerated
     */
    private String productStore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.favorable_rate
     *
     * @mbggenerated
     */
    private Double favorableRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_category
     *
     * @mbggenerated
     */
    private Byte evaluateCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.user_nick
     *
     * @mbggenerated
     */
    private String userNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_info
     *
     * @mbggenerated
     */
    private String evaluateInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_time
     *
     * @mbggenerated
     */
    private Date evaluateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_dimension_one
     *
     * @mbggenerated
     */
    private String evaluateDimensionOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_dimension_two
     *
     * @mbggenerated
     */
    private String evaluateDimensionTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_dimension_three
     *
     * @mbggenerated
     */
    private String evaluateDimensionThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_insight.evaluate_dimension_fire
     *
     * @mbggenerated
     */
    private String evaluateDimensionFire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.id
     *
     * @return the value of product_insight.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.id
     *
     * @param id the value for product_insight.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.product_category
     *
     * @return the value of product_insight.product_category
     *
     * @mbggenerated
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.product_category
     *
     * @param productCategory the value for product_insight.product_category
     *
     * @mbggenerated
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.product_brand
     *
     * @return the value of product_insight.product_brand
     *
     * @mbggenerated
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.product_brand
     *
     * @param productBrand the value for product_insight.product_brand
     *
     * @mbggenerated
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.product_platform
     *
     * @return the value of product_insight.product_platform
     *
     * @mbggenerated
     */
    public String getProductPlatform() {
        return productPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.product_platform
     *
     * @param productPlatform the value for product_insight.product_platform
     *
     * @mbggenerated
     */
    public void setProductPlatform(String productPlatform) {
        this.productPlatform = productPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.product_model
     *
     * @return the value of product_insight.product_model
     *
     * @mbggenerated
     */
    public String getProductModel() {
        return productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.product_model
     *
     * @param productModel the value for product_insight.product_model
     *
     * @mbggenerated
     */
    public void setProductModel(String productModel) {
        this.productModel = productModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.product_store
     *
     * @return the value of product_insight.product_store
     *
     * @mbggenerated
     */
    public String getProductStore() {
        return productStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.product_store
     *
     * @param productStore the value for product_insight.product_store
     *
     * @mbggenerated
     */
    public void setProductStore(String productStore) {
        this.productStore = productStore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.favorable_rate
     *
     * @return the value of product_insight.favorable_rate
     *
     * @mbggenerated
     */
    public Double getFavorableRate() {
        return favorableRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.favorable_rate
     *
     * @param favorableRate the value for product_insight.favorable_rate
     *
     * @mbggenerated
     */
    public void setFavorableRate(Double favorableRate) {
        this.favorableRate = favorableRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_category
     *
     * @return the value of product_insight.evaluate_category
     *
     * @mbggenerated
     */
    public Byte getEvaluateCategory() {
        return evaluateCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_category
     *
     * @param evaluateCategory the value for product_insight.evaluate_category
     *
     * @mbggenerated
     */
    public void setEvaluateCategory(Byte evaluateCategory) {
        this.evaluateCategory = evaluateCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.user_nick
     *
     * @return the value of product_insight.user_nick
     *
     * @mbggenerated
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.user_nick
     *
     * @param userNick the value for product_insight.user_nick
     *
     * @mbggenerated
     */
    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_info
     *
     * @return the value of product_insight.evaluate_info
     *
     * @mbggenerated
     */
    public String getEvaluateInfo() {
        return evaluateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_info
     *
     * @param evaluateInfo the value for product_insight.evaluate_info
     *
     * @mbggenerated
     */
    public void setEvaluateInfo(String evaluateInfo) {
        this.evaluateInfo = evaluateInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_time
     *
     * @return the value of product_insight.evaluate_time
     *
     * @mbggenerated
     */
    public Date getEvaluateTime() {
        return evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_time
     *
     * @param evaluateTime the value for product_insight.evaluate_time
     *
     * @mbggenerated
     */
    public void setEvaluateTime(Date evaluateTime) {
        this.evaluateTime = evaluateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_dimension_one
     *
     * @return the value of product_insight.evaluate_dimension_one
     *
     * @mbggenerated
     */
    public String getEvaluateDimensionOne() {
        return evaluateDimensionOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_dimension_one
     *
     * @param evaluateDimensionOne the value for product_insight.evaluate_dimension_one
     *
     * @mbggenerated
     */
    public void setEvaluateDimensionOne(String evaluateDimensionOne) {
        this.evaluateDimensionOne = evaluateDimensionOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_dimension_two
     *
     * @return the value of product_insight.evaluate_dimension_two
     *
     * @mbggenerated
     */
    public String getEvaluateDimensionTwo() {
        return evaluateDimensionTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_dimension_two
     *
     * @param evaluateDimensionTwo the value for product_insight.evaluate_dimension_two
     *
     * @mbggenerated
     */
    public void setEvaluateDimensionTwo(String evaluateDimensionTwo) {
        this.evaluateDimensionTwo = evaluateDimensionTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_dimension_three
     *
     * @return the value of product_insight.evaluate_dimension_three
     *
     * @mbggenerated
     */
    public String getEvaluateDimensionThree() {
        return evaluateDimensionThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_dimension_three
     *
     * @param evaluateDimensionThree the value for product_insight.evaluate_dimension_three
     *
     * @mbggenerated
     */
    public void setEvaluateDimensionThree(String evaluateDimensionThree) {
        this.evaluateDimensionThree = evaluateDimensionThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_insight.evaluate_dimension_fire
     *
     * @return the value of product_insight.evaluate_dimension_fire
     *
     * @mbggenerated
     */
    public String getEvaluateDimensionFire() {
        return evaluateDimensionFire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_insight.evaluate_dimension_fire
     *
     * @param evaluateDimensionFire the value for product_insight.evaluate_dimension_fire
     *
     * @mbggenerated
     */
    public void setEvaluateDimensionFire(String evaluateDimensionFire) {
        this.evaluateDimensionFire = evaluateDimensionFire;
    }
}