package com.yz.sophia.insight.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductInsightExample {

    protected int offset = 0;

    protected int pageSize = 10;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public ProductInsightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNull() {
            addCriterion("product_category is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNotNull() {
            addCriterion("product_category is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryEqualTo(String value) {
            addCriterion("product_category =", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotEqualTo(String value) {
            addCriterion("product_category <>", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThan(String value) {
            addCriterion("product_category >", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("product_category >=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThan(String value) {
            addCriterion("product_category <", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThanOrEqualTo(String value) {
            addCriterion("product_category <=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLike(String value) {
            addCriterion("product_category like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotLike(String value) {
            addCriterion("product_category not like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIn(List<String> values) {
            addCriterion("product_category in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotIn(List<String> values) {
            addCriterion("product_category not in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryBetween(String value1, String value2) {
            addCriterion("product_category between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotBetween(String value1, String value2) {
            addCriterion("product_category not between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNull() {
            addCriterion("product_brand is null");
            return (Criteria) this;
        }

        public Criteria andProductBrandIsNotNull() {
            addCriterion("product_brand is not null");
            return (Criteria) this;
        }

        public Criteria andProductBrandEqualTo(String value) {
            addCriterion("product_brand =", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotEqualTo(String value) {
            addCriterion("product_brand <>", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThan(String value) {
            addCriterion("product_brand >", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandGreaterThanOrEqualTo(String value) {
            addCriterion("product_brand >=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThan(String value) {
            addCriterion("product_brand <", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLessThanOrEqualTo(String value) {
            addCriterion("product_brand <=", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandLike(String value) {
            addCriterion("product_brand like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotLike(String value) {
            addCriterion("product_brand not like", value, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandIn(List<String> values) {
            addCriterion("product_brand in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotIn(List<String> values) {
            addCriterion("product_brand not in", values, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandBetween(String value1, String value2) {
            addCriterion("product_brand between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductBrandNotBetween(String value1, String value2) {
            addCriterion("product_brand not between", value1, value2, "productBrand");
            return (Criteria) this;
        }

        public Criteria andProductPlatformIsNull() {
            addCriterion("product_platform is null");
            return (Criteria) this;
        }

        public Criteria andProductPlatformIsNotNull() {
            addCriterion("product_platform is not null");
            return (Criteria) this;
        }

        public Criteria andProductPlatformEqualTo(String value) {
            addCriterion("product_platform =", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformNotEqualTo(String value) {
            addCriterion("product_platform <>", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformGreaterThan(String value) {
            addCriterion("product_platform >", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("product_platform >=", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformLessThan(String value) {
            addCriterion("product_platform <", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformLessThanOrEqualTo(String value) {
            addCriterion("product_platform <=", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformLike(String value) {
            addCriterion("product_platform like", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformNotLike(String value) {
            addCriterion("product_platform not like", value, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformIn(List<String> values) {
            addCriterion("product_platform in", values, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformNotIn(List<String> values) {
            addCriterion("product_platform not in", values, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformBetween(String value1, String value2) {
            addCriterion("product_platform between", value1, value2, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductPlatformNotBetween(String value1, String value2) {
            addCriterion("product_platform not between", value1, value2, "productPlatform");
            return (Criteria) this;
        }

        public Criteria andProductModelIsNull() {
            addCriterion("product_model is null");
            return (Criteria) this;
        }

        public Criteria andProductModelIsNotNull() {
            addCriterion("product_model is not null");
            return (Criteria) this;
        }

        public Criteria andProductModelEqualTo(String value) {
            addCriterion("product_model =", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotEqualTo(String value) {
            addCriterion("product_model <>", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelGreaterThan(String value) {
            addCriterion("product_model >", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelGreaterThanOrEqualTo(String value) {
            addCriterion("product_model >=", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLessThan(String value) {
            addCriterion("product_model <", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLessThanOrEqualTo(String value) {
            addCriterion("product_model <=", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelLike(String value) {
            addCriterion("product_model like", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotLike(String value) {
            addCriterion("product_model not like", value, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelIn(List<String> values) {
            addCriterion("product_model in", values, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotIn(List<String> values) {
            addCriterion("product_model not in", values, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelBetween(String value1, String value2) {
            addCriterion("product_model between", value1, value2, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductModelNotBetween(String value1, String value2) {
            addCriterion("product_model not between", value1, value2, "productModel");
            return (Criteria) this;
        }

        public Criteria andProductStoreIsNull() {
            addCriterion("product_store is null");
            return (Criteria) this;
        }

        public Criteria andProductStoreIsNotNull() {
            addCriterion("product_store is not null");
            return (Criteria) this;
        }

        public Criteria andProductStoreEqualTo(String value) {
            addCriterion("product_store =", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreNotEqualTo(String value) {
            addCriterion("product_store <>", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreGreaterThan(String value) {
            addCriterion("product_store >", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreGreaterThanOrEqualTo(String value) {
            addCriterion("product_store >=", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreLessThan(String value) {
            addCriterion("product_store <", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreLessThanOrEqualTo(String value) {
            addCriterion("product_store <=", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreLike(String value) {
            addCriterion("product_store like", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreNotLike(String value) {
            addCriterion("product_store not like", value, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreIn(List<String> values) {
            addCriterion("product_store in", values, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreNotIn(List<String> values) {
            addCriterion("product_store not in", values, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreBetween(String value1, String value2) {
            addCriterion("product_store between", value1, value2, "productStore");
            return (Criteria) this;
        }

        public Criteria andProductStoreNotBetween(String value1, String value2) {
            addCriterion("product_store not between", value1, value2, "productStore");
            return (Criteria) this;
        }

        public Criteria andFavorableRateIsNull() {
            addCriterion("favorable_rate is null");
            return (Criteria) this;
        }

        public Criteria andFavorableRateIsNotNull() {
            addCriterion("favorable_rate is not null");
            return (Criteria) this;
        }

        public Criteria andFavorableRateEqualTo(Double value) {
            addCriterion("favorable_rate =", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateNotEqualTo(Double value) {
            addCriterion("favorable_rate <>", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateGreaterThan(Double value) {
            addCriterion("favorable_rate >", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateGreaterThanOrEqualTo(Double value) {
            addCriterion("favorable_rate >=", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateLessThan(Double value) {
            addCriterion("favorable_rate <", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateLessThanOrEqualTo(Double value) {
            addCriterion("favorable_rate <=", value, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateIn(List<Double> values) {
            addCriterion("favorable_rate in", values, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateNotIn(List<Double> values) {
            addCriterion("favorable_rate not in", values, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateBetween(Double value1, Double value2) {
            addCriterion("favorable_rate between", value1, value2, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andFavorableRateNotBetween(Double value1, Double value2) {
            addCriterion("favorable_rate not between", value1, value2, "favorableRate");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryIsNull() {
            addCriterion("evaluate_category is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryIsNotNull() {
            addCriterion("evaluate_category is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryEqualTo(Byte value) {
            addCriterion("evaluate_category =", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryNotEqualTo(Byte value) {
            addCriterion("evaluate_category <>", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryGreaterThan(Byte value) {
            addCriterion("evaluate_category >", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryGreaterThanOrEqualTo(Byte value) {
            addCriterion("evaluate_category >=", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryLessThan(Byte value) {
            addCriterion("evaluate_category <", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryLessThanOrEqualTo(Byte value) {
            addCriterion("evaluate_category <=", value, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryIn(List<Byte> values) {
            addCriterion("evaluate_category in", values, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryNotIn(List<Byte> values) {
            addCriterion("evaluate_category not in", values, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryBetween(Byte value1, Byte value2) {
            addCriterion("evaluate_category between", value1, value2, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andEvaluateCategoryNotBetween(Byte value1, Byte value2) {
            addCriterion("evaluate_category not between", value1, value2, "evaluateCategory");
            return (Criteria) this;
        }

        public Criteria andUserNickIsNull() {
            addCriterion("user_nick is null");
            return (Criteria) this;
        }

        public Criteria andUserNickIsNotNull() {
            addCriterion("user_nick is not null");
            return (Criteria) this;
        }

        public Criteria andUserNickEqualTo(String value) {
            addCriterion("user_nick =", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickNotEqualTo(String value) {
            addCriterion("user_nick <>", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickGreaterThan(String value) {
            addCriterion("user_nick >", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickGreaterThanOrEqualTo(String value) {
            addCriterion("user_nick >=", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickLessThan(String value) {
            addCriterion("user_nick <", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickLessThanOrEqualTo(String value) {
            addCriterion("user_nick <=", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickLike(String value) {
            addCriterion("user_nick like", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickNotLike(String value) {
            addCriterion("user_nick not like", value, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickIn(List<String> values) {
            addCriterion("user_nick in", values, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickNotIn(List<String> values) {
            addCriterion("user_nick not in", values, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickBetween(String value1, String value2) {
            addCriterion("user_nick between", value1, value2, "userNick");
            return (Criteria) this;
        }

        public Criteria andUserNickNotBetween(String value1, String value2) {
            addCriterion("user_nick not between", value1, value2, "userNick");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoIsNull() {
            addCriterion("evaluate_info is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoIsNotNull() {
            addCriterion("evaluate_info is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoEqualTo(String value) {
            addCriterion("evaluate_info =", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoNotEqualTo(String value) {
            addCriterion("evaluate_info <>", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoGreaterThan(String value) {
            addCriterion("evaluate_info >", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_info >=", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoLessThan(String value) {
            addCriterion("evaluate_info <", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoLessThanOrEqualTo(String value) {
            addCriterion("evaluate_info <=", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoLike(String value) {
            addCriterion("evaluate_info like", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoNotLike(String value) {
            addCriterion("evaluate_info not like", value, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoIn(List<String> values) {
            addCriterion("evaluate_info in", values, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoNotIn(List<String> values) {
            addCriterion("evaluate_info not in", values, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoBetween(String value1, String value2) {
            addCriterion("evaluate_info between", value1, value2, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateInfoNotBetween(String value1, String value2) {
            addCriterion("evaluate_info not between", value1, value2, "evaluateInfo");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIsNull() {
            addCriterion("evaluate_time is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIsNotNull() {
            addCriterion("evaluate_time is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeEqualTo(Date value) {
            addCriterion("evaluate_time =", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotEqualTo(Date value) {
            addCriterion("evaluate_time <>", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeGreaterThan(Date value) {
            addCriterion("evaluate_time >", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("evaluate_time >=", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeLessThan(Date value) {
            addCriterion("evaluate_time <", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeLessThanOrEqualTo(Date value) {
            addCriterion("evaluate_time <=", value, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeIn(List<Date> values) {
            addCriterion("evaluate_time in", values, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotIn(List<Date> values) {
            addCriterion("evaluate_time not in", values, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeBetween(Date value1, Date value2) {
            addCriterion("evaluate_time between", value1, value2, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateTimeNotBetween(Date value1, Date value2) {
            addCriterion("evaluate_time not between", value1, value2, "evaluateTime");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneIsNull() {
            addCriterion("evaluate_dimension_one is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneIsNotNull() {
            addCriterion("evaluate_dimension_one is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneEqualTo(String value) {
            addCriterion("evaluate_dimension_one =", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneNotEqualTo(String value) {
            addCriterion("evaluate_dimension_one <>", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneGreaterThan(String value) {
            addCriterion("evaluate_dimension_one >", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_one >=", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneLessThan(String value) {
            addCriterion("evaluate_dimension_one <", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneLessThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_one <=", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneLike(String value) {
            addCriterion("evaluate_dimension_one like", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneNotLike(String value) {
            addCriterion("evaluate_dimension_one not like", value, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneIn(List<String> values) {
            addCriterion("evaluate_dimension_one in", values, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneNotIn(List<String> values) {
            addCriterion("evaluate_dimension_one not in", values, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_one between", value1, value2, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionOneNotBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_one not between", value1, value2, "evaluateDimensionOne");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoIsNull() {
            addCriterion("evaluate_dimension_two is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoIsNotNull() {
            addCriterion("evaluate_dimension_two is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoEqualTo(String value) {
            addCriterion("evaluate_dimension_two =", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoNotEqualTo(String value) {
            addCriterion("evaluate_dimension_two <>", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoGreaterThan(String value) {
            addCriterion("evaluate_dimension_two >", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_two >=", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoLessThan(String value) {
            addCriterion("evaluate_dimension_two <", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoLessThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_two <=", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoLike(String value) {
            addCriterion("evaluate_dimension_two like", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoNotLike(String value) {
            addCriterion("evaluate_dimension_two not like", value, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoIn(List<String> values) {
            addCriterion("evaluate_dimension_two in", values, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoNotIn(List<String> values) {
            addCriterion("evaluate_dimension_two not in", values, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_two between", value1, value2, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionTwoNotBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_two not between", value1, value2, "evaluateDimensionTwo");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeIsNull() {
            addCriterion("evaluate_dimension_three is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeIsNotNull() {
            addCriterion("evaluate_dimension_three is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeEqualTo(String value) {
            addCriterion("evaluate_dimension_three =", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeNotEqualTo(String value) {
            addCriterion("evaluate_dimension_three <>", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeGreaterThan(String value) {
            addCriterion("evaluate_dimension_three >", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_three >=", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeLessThan(String value) {
            addCriterion("evaluate_dimension_three <", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeLessThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_three <=", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeLike(String value) {
            addCriterion("evaluate_dimension_three like", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeNotLike(String value) {
            addCriterion("evaluate_dimension_three not like", value, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeIn(List<String> values) {
            addCriterion("evaluate_dimension_three in", values, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeNotIn(List<String> values) {
            addCriterion("evaluate_dimension_three not in", values, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_three between", value1, value2, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionThreeNotBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_three not between", value1, value2, "evaluateDimensionThree");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireIsNull() {
            addCriterion("evaluate_dimension_fire is null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireIsNotNull() {
            addCriterion("evaluate_dimension_fire is not null");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireEqualTo(String value) {
            addCriterion("evaluate_dimension_fire =", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireNotEqualTo(String value) {
            addCriterion("evaluate_dimension_fire <>", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireGreaterThan(String value) {
            addCriterion("evaluate_dimension_fire >", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireGreaterThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_fire >=", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireLessThan(String value) {
            addCriterion("evaluate_dimension_fire <", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireLessThanOrEqualTo(String value) {
            addCriterion("evaluate_dimension_fire <=", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireLike(String value) {
            addCriterion("evaluate_dimension_fire like", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireNotLike(String value) {
            addCriterion("evaluate_dimension_fire not like", value, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireIn(List<String> values) {
            addCriterion("evaluate_dimension_fire in", values, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireNotIn(List<String> values) {
            addCriterion("evaluate_dimension_fire not in", values, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_fire between", value1, value2, "evaluateDimensionFire");
            return (Criteria) this;
        }

        public Criteria andEvaluateDimensionFireNotBetween(String value1, String value2) {
            addCriterion("evaluate_dimension_fire not between", value1, value2, "evaluateDimensionFire");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_insight
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_insight
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}