package com.yz.sophia.stargaze.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CockpitStatisticalChartsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public CockpitStatisticalChartsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChartCodeIsNull() {
            addCriterion("chart_code is null");
            return (Criteria) this;
        }

        public Criteria andChartCodeIsNotNull() {
            addCriterion("chart_code is not null");
            return (Criteria) this;
        }

        public Criteria andChartCodeEqualTo(String value) {
            addCriterion("chart_code =", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeNotEqualTo(String value) {
            addCriterion("chart_code <>", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeGreaterThan(String value) {
            addCriterion("chart_code >", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeGreaterThanOrEqualTo(String value) {
            addCriterion("chart_code >=", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeLessThan(String value) {
            addCriterion("chart_code <", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeLessThanOrEqualTo(String value) {
            addCriterion("chart_code <=", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeLike(String value) {
            addCriterion("chart_code like", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeNotLike(String value) {
            addCriterion("chart_code not like", value, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeIn(List<String> values) {
            addCriterion("chart_code in", values, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeNotIn(List<String> values) {
            addCriterion("chart_code not in", values, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeBetween(String value1, String value2) {
            addCriterion("chart_code between", value1, value2, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartCodeNotBetween(String value1, String value2) {
            addCriterion("chart_code not between", value1, value2, "chartCode");
            return (Criteria) this;
        }

        public Criteria andChartNameIsNull() {
            addCriterion("chart_name is null");
            return (Criteria) this;
        }

        public Criteria andChartNameIsNotNull() {
            addCriterion("chart_name is not null");
            return (Criteria) this;
        }

        public Criteria andChartNameEqualTo(String value) {
            addCriterion("chart_name =", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameNotEqualTo(String value) {
            addCriterion("chart_name <>", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameGreaterThan(String value) {
            addCriterion("chart_name >", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameGreaterThanOrEqualTo(String value) {
            addCriterion("chart_name >=", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameLessThan(String value) {
            addCriterion("chart_name <", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameLessThanOrEqualTo(String value) {
            addCriterion("chart_name <=", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameLike(String value) {
            addCriterion("chart_name like", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameNotLike(String value) {
            addCriterion("chart_name not like", value, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameIn(List<String> values) {
            addCriterion("chart_name in", values, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameNotIn(List<String> values) {
            addCriterion("chart_name not in", values, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameBetween(String value1, String value2) {
            addCriterion("chart_name between", value1, value2, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartNameNotBetween(String value1, String value2) {
            addCriterion("chart_name not between", value1, value2, "chartName");
            return (Criteria) this;
        }

        public Criteria andChartTypeIsNull() {
            addCriterion("chart_type is null");
            return (Criteria) this;
        }

        public Criteria andChartTypeIsNotNull() {
            addCriterion("chart_type is not null");
            return (Criteria) this;
        }

        public Criteria andChartTypeEqualTo(int value) {
            addCriterion("chart_type =", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeNotEqualTo(int value) {
            addCriterion("chart_type <>", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeGreaterThan(int value) {
            addCriterion("chart_type >", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeGreaterThanOrEqualTo(int value) {
            addCriterion("chart_type >=", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeLessThan(int value) {
            addCriterion("chart_type <", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeLessThanOrEqualTo(int value) {
            addCriterion("chart_type <=", value, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeIn(List<Integer> values) {
            addCriterion("chart_type in", values, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeNotIn(List<Integer> values) {
            addCriterion("chart_type not in", values, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeBetween(int value1, int value2) {
            addCriterion("chart_type between", value1, value2, "chartType");
            return (Criteria) this;
        }

        public Criteria andChartTypeNotBetween(int value1, int value2) {
            addCriterion("chart_type not between", value1, value2, "chartType");
            return (Criteria) this;
        }

        public Criteria andDataSourceIsNull() {
            addCriterion("data_source is null");
            return (Criteria) this;
        }

        public Criteria andDataSourceIsNotNull() {
            addCriterion("data_source is not null");
            return (Criteria) this;
        }

        public Criteria andDataSourceEqualTo(String value) {
            addCriterion("data_source =", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotEqualTo(String value) {
            addCriterion("data_source <>", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceGreaterThan(String value) {
            addCriterion("data_source >", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceGreaterThanOrEqualTo(String value) {
            addCriterion("data_source >=", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceLessThan(String value) {
            addCriterion("data_source <", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceLessThanOrEqualTo(String value) {
            addCriterion("data_source <=", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceLike(String value) {
            addCriterion("data_source like", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotLike(String value) {
            addCriterion("data_source not like", value, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceIn(List<String> values) {
            addCriterion("data_source in", values, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotIn(List<String> values) {
            addCriterion("data_source not in", values, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceBetween(String value1, String value2) {
            addCriterion("data_source between", value1, value2, "dataSource");
            return (Criteria) this;
        }

        public Criteria andDataSourceNotBetween(String value1, String value2) {
            addCriterion("data_source not between", value1, value2, "dataSource");
            return (Criteria) this;
        }

        public Criteria andChartLocationIsNull() {
            addCriterion("chart_location is null");
            return (Criteria) this;
        }

        public Criteria andChartLocationIsNotNull() {
            addCriterion("chart_location is not null");
            return (Criteria) this;
        }

        public Criteria andChartLocationEqualTo(int value) {
            addCriterion("chart_location =", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationNotEqualTo(int value) {
            addCriterion("chart_location <>", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationGreaterThan(int value) {
            addCriterion("chart_location >", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationGreaterThanOrEqualTo(int value) {
            addCriterion("chart_location >=", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationLessThan(int value) {
            addCriterion("chart_location <", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationLessThanOrEqualTo(int value) {
            addCriterion("chart_location <=", value, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationIn(List<Integer> values) {
            addCriterion("chart_location in", values, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationNotIn(List<Integer> values) {
            addCriterion("chart_location not in", values, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationBetween(int value1, int value2) {
            addCriterion("chart_location between", value1, value2, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andChartLocationNotBetween(int value1, int value2) {
            addCriterion("chart_location not between", value1, value2, "chartLocation");
            return (Criteria) this;
        }

        public Criteria andParentTitleIsNull() {
            addCriterion("parent_title is null");
            return (Criteria) this;
        }

        public Criteria andParentTitleIsNotNull() {
            addCriterion("parent_title is not null");
            return (Criteria) this;
        }

        public Criteria andParentTitleEqualTo(int value) {
            addCriterion("parent_title =", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleNotEqualTo(int value) {
            addCriterion("parent_title <>", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleGreaterThan(int value) {
            addCriterion("parent_title >", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleGreaterThanOrEqualTo(int value) {
            addCriterion("parent_title >=", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleLessThan(int value) {
            addCriterion("parent_title <", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleLessThanOrEqualTo(int value) {
            addCriterion("parent_title <=", value, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleIn(List<Integer> values) {
            addCriterion("parent_title in", values, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleNotIn(List<Integer> values) {
            addCriterion("parent_title not in", values, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleBetween(int value1, int value2) {
            addCriterion("parent_title between", value1, value2, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andParentTitleNotBetween(int value1, int value2) {
            addCriterion("parent_title not between", value1, value2, "parentTitle");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeIsNull() {
            addCriterion("sub_title_code is null");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeIsNotNull() {
            addCriterion("sub_title_code is not null");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeEqualTo(String value) {
            addCriterion("sub_title_code =", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeNotEqualTo(String value) {
            addCriterion("sub_title_code <>", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeGreaterThan(String value) {
            addCriterion("sub_title_code >", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sub_title_code >=", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeLessThan(String value) {
            addCriterion("sub_title_code <", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeLessThanOrEqualTo(String value) {
            addCriterion("sub_title_code <=", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeLike(String value) {
            addCriterion("sub_title_code like", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeNotLike(String value) {
            addCriterion("sub_title_code not like", value, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeIn(List<String> values) {
            addCriterion("sub_title_code in", values, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeNotIn(List<String> values) {
            addCriterion("sub_title_code not in", values, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeBetween(String value1, String value2) {
            addCriterion("sub_title_code between", value1, value2, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andSubTitleCodeNotBetween(String value1, String value2) {
            addCriterion("sub_title_code not between", value1, value2, "subTitleCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cockpit_statistical_charts
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}