package com.yz.sophia.stargaze.model.po;

public class PoiArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.dataid
     *
     * @mbggenerated
     */
    private Long dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.lng
     *
     * @mbggenerated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.altitude
     *
     * @mbggenerated
     */
    private Integer altitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.province_code
     *
     * @mbggenerated
     */
    private Integer provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poi_area.city_code
     *
     * @mbggenerated
     */
    private Integer cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.dataid
     *
     * @return the value of poi_area.dataid
     *
     * @mbggenerated
     */
    public Long getDataid() {
        return dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.dataid
     *
     * @param dataid the value for poi_area.dataid
     *
     * @mbggenerated
     */
    public void setDataid(Long dataid) {
        this.dataid = dataid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.province_name
     *
     * @return the value of poi_area.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.province_name
     *
     * @param provinceName the value for poi_area.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.lng
     *
     * @return the value of poi_area.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.lng
     *
     * @param lng the value for poi_area.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.lat
     *
     * @return the value of poi_area.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.lat
     *
     * @param lat the value for poi_area.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.altitude
     *
     * @return the value of poi_area.altitude
     *
     * @mbggenerated
     */
    public Integer getAltitude() {
        return altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.altitude
     *
     * @param altitude the value for poi_area.altitude
     *
     * @mbggenerated
     */
    public void setAltitude(Integer altitude) {
        this.altitude = altitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.address
     *
     * @return the value of poi_area.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.address
     *
     * @param address the value for poi_area.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.description
     *
     * @return the value of poi_area.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.description
     *
     * @param description the value for poi_area.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.province_code
     *
     * @return the value of poi_area.province_code
     *
     * @mbggenerated
     */
    public Integer getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.province_code
     *
     * @param provinceCode the value for poi_area.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(Integer provinceCode) {
        this.provinceCode = provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.city_name
     *
     * @return the value of poi_area.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.city_name
     *
     * @param cityName the value for poi_area.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poi_area.city_code
     *
     * @return the value of poi_area.city_code
     *
     * @mbggenerated
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poi_area.city_code
     *
     * @param cityCode the value for poi_area.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }
}